spring.application.name=gym

spring.profiles.active=local

# ===============================
# JPA/Hibernate Configuration
# ===============================
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

#spring.jpa.show-sql=true

# ===============================
# Logging
# ===============================
# Enable ANSI colors
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%2p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} [%thread] %-5level %logger{36} - [%X{transactionId}] %msg%n

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=when_authorized
management.endpoint.info.enabled=true
management.info.env.enabled=true

# ===============================
# Basic information
# ===============================
info.app.name=My Gym Application
info.app.description=A comprehensive gym management system
info.app.version=1.0.0
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@

# ===============================
# Custom information
# ===============================
info.company.name=EPAM
info.company.website=https://epam.com
info.developer.name=Felipe Munevar
info.developer.email=felipemunevarn@gmail.com

# ===============================
# Expose Prometheus endpoint
# ===============================
#management.endpoint.prometheus.enabled=true
#management.metrics.export.prometheus.enabled=true

# ===============================
# Optional: Custom metrics prefix
# ===============================
management.metrics.tags.application=gym-management-system